// Fixtures generated by scripts/gen-bot-avatar-fixtures.mjs, which imports
// `blobatar` the exact way the desktop does (apps/desktop/src/sdk/index.ts:
// 1750's `blobatarSvg` IS the npm package's own `blobatar` from
// 'blobatar/blob'), called raw — independent of this module's own port of
// avatar.tsx's seed-resolution logic, so a divergence here is a real bug,
// not a fixture that baked the same mistake in twice.

import { describe, expect, it } from 'vitest'

import fixtures from './__fixtures__/bot-avatar.json'
import { blobShapeString, botAvatarSvg, isBlobShape, parseBlobShape } from './bot-avatar'

describe('botAvatarSvg', () => {
  it('a plain name-seeded face equals the desktop-imported blobatar output', () => {
    const fixture = fixtures['plain-name-seed']

    expect(botAvatarSvg('researcher', { size: 40 })).toBe(fixture.svg)
  })

  it('a different name produces a different (still matching) fixture', () => {
    const fixture = fixtures['another-plain-name-seed']

    expect(botAvatarSvg('coder', { size: 40 })).toBe(fixture.svg)
  })

  it('a locked seed (shape "blobatar:<seed>") follows the seed, not the name', () => {
    const fixture = fixtures['locked-seed']

    expect(botAvatarSvg('some-other-bot-name', { shape: 'blobatar:pinned-seed-value', size: 40 })).toBe(fixture.svg)
  })

  it('a locked seed plus a pinned silhouette ("blobatar:<seed>:<kind>") matches the traits override', () => {
    const fixture = fixtures['locked-seed-plus-pinned-silhouette-sun']

    expect(botAvatarSvg('irrelevant', { shape: 'blobatar:pinned-seed-value:sun', size: 40 })).toBe(fixture.svg)
  })

  it('a pinned silhouette with no locked seed ("blobatar::<kind>") still follows the name', () => {
    const fixture = fixtures['pinned-silhouette-triangle-seed-follows-name']

    expect(botAvatarSvg('researcher', { shape: 'blobatar::triangle', size: 40 })).toBe(fixture.svg)
  })

  it('size is forwarded to blobatar unchanged', () => {
    const fixture = fixtures['default-size-96']

    expect(botAvatarSvg('researcher', { size: 96 })).toBe(fixture.svg)
  })

  it('an unrecognized :kind segment is dropped, same as no kind at all', () => {
    const fixture = fixtures['locked-seed']

    expect(botAvatarSvg('irrelevant', { shape: 'blobatar:pinned-seed-value:not-a-real-kind', size: 40 })).toBe(
      fixture.svg
    )
  })
})

describe('parseBlobShape (avatar.tsx:172-182 port)', () => {
  it('bare "blobatar" follows the name, no kind', () => {
    expect(parseBlobShape('blobatar', 'researcher')).toEqual({ kind: '', seed: 'researcher', seedPart: '' })
  })

  it('no shape at all falls back to the name', () => {
    expect(parseBlobShape(null, 'researcher')).toEqual({ kind: '', seed: 'researcher', seedPart: '' })
  })

  it('no shape and no name falls back to the literal "agent"', () => {
    expect(parseBlobShape(null, undefined)).toEqual({ kind: '', seed: 'agent', seedPart: '' })
  })

  it('"blobatar:<seed>" locks the seed', () => {
    expect(parseBlobShape('blobatar:pinned', 'researcher')).toEqual({ kind: '', seed: 'pinned', seedPart: 'pinned' })
  })

  it('"blobatar:<seed>:<kind>" locks both', () => {
    expect(parseBlobShape('blobatar:pinned:sun', 'researcher')).toEqual({
      kind: 'sun',
      seed: 'pinned',
      seedPart: 'pinned'
    })
  })

  it('"blobatar::<kind>" pins the silhouette but the seed still follows the name', () => {
    expect(parseBlobShape('blobatar::sun', 'researcher')).toEqual({ kind: 'sun', seed: 'researcher', seedPart: '' })
  })
})

describe('blobShapeString (avatar.tsx:184-190 port) / isBlobShape (avatar.tsx:159-161 port)', () => {
  it('round-trips through parseBlobShape', () => {
    expect(blobShapeString('pinned', 'sun')).toBe('blobatar:pinned:sun')
    expect(blobShapeString('pinned', '')).toBe('blobatar:pinned')
    expect(blobShapeString('', '')).toBe('blobatar')
  })

  it('recognizes every blobatar-prefixed shape string', () => {
    expect(isBlobShape('blobatar')).toBe(true)
    expect(isBlobShape('blobatar:seed')).toBe(true)
    expect(isBlobShape('sigil-3')).toBe(false)
    expect(isBlobShape(null)).toBe(false)
  })
})
