// D22.5 / scripts/build-release-apk.sh: injects a `release` signingConfig
// into the CNG-generated android/app/build.gradle at prebuild time, reading
// the keystore path and passwords from the environment at GRADLE BUILD
// TIME (`System.getenv(...)` in the injected Groovy), never at prebuild
// time. This file never sees, stores, or writes the actual secret values —
// only the four env var NAMES are baked into build.gradle, which is itself
// git-ignored (CNG output, regenerated by every `expo prebuild`).
//
// Without this plugin, the Expo/RN template's own default release
// buildType signs with the debug keystore (see the template's own comment:
// "Caution! In production, you need to generate your own keystore file."),
// which cannot be distributed as a real release artifact.
const { withAppBuildGradle } = require('@expo/config-plugins')

const RELEASE_SIGNING_CONFIG = `        release {
            if (System.getenv("HERMES_KEYSTORE_PATH")) {
                storeFile file(System.getenv("HERMES_KEYSTORE_PATH"))
                storePassword System.getenv("HERMES_KEYSTORE_PASSWORD")
                keyAlias System.getenv("HERMES_KEY_ALIAS")
                keyPassword System.getenv("HERMES_KEY_PASSWORD")
            }
        }
`

function withReleaseSigning(config) {
  return withAppBuildGradle(config, config => {
    let contents = config.modResults.contents

    if (contents.includes('HERMES_KEYSTORE_PATH')) {
      return config
    }

    const signingConfigsMarker = /signingConfigs\s*\{\n(\s*debug\s*\{[\s\S]*?\n\s*\}\n)/
    const match = contents.match(signingConfigsMarker)

    if (!match) {
      throw new Error(
        'withReleaseSigning: could not find the generated signingConfigs { debug { ... } } block ' +
          'in android/app/build.gradle to anchor the release signingConfig on. The Expo/RN template ' +
          'this was written against may have changed shape.'
      )
    }

    contents = contents.replace(match[0], match[0] + RELEASE_SIGNING_CONFIG)

    const releaseBuildTypeMarker =
      'release {\n            // Caution! In production, you need to generate your own keystore file.\n            // see https://reactnative.dev/docs/signed-apk-android.\n            signingConfig signingConfigs.debug'

    if (!contents.includes(releaseBuildTypeMarker)) {
      throw new Error(
        'withReleaseSigning: could not find the generated release buildType block in ' +
          'android/app/build.gradle to point at signingConfigs.release. The Expo/RN template this ' +
          'was written against may have changed shape.'
      )
    }

    contents = contents.replace(
      releaseBuildTypeMarker,
      releaseBuildTypeMarker.replace('signingConfigs.debug', 'signingConfigs.release')
    )

    config.modResults.contents = contents

    return config
  })
}

module.exports = withReleaseSigning
