// Permits cleartext (plain `http://`) traffic, and commits that decision to
// the repo instead of leaving it as a hand-edited file in the git-ignored
// `android/` folder.
//
// Why it is needed at all: `targetSdkVersion` is 36, and since API 28 Android
// defaults `cleartextTrafficPermitted` to **false**. A real release APK
// therefore cannot reach ANY `http://` gateway — every `hermes serve` a user
// runs, because `hermes serve` has no TLS option at all (checked
// `hermes_cli/subcommands/serve.py` and `hermes_cli/web_server.py`: no
// `--cert`/`--key`/`ssl_*`). Requiring HTTPS would mean requiring every user
// to front their gateway with a reverse proxy before the app works once.
// Decision taken: permit cleartext, and say so in the UI (the connect
// screen's unencrypted-connection warning) and in `docs/CONNECTING.md`.
//
// Why `base-config` and not per-address `domain-config` entries: Android's
// network security config matches hostnames and literal IP addresses only —
// `<domain>` takes a host, never a CIDR range. There is no way to write "any
// RFC 1918 LAN address" or "any tailnet address", and the set of gateway
// addresses is by definition the user's, unknown at build time. A hard-coded
// `10.0.2.2` entry (which is what the hand-added file in `android/` had)
// permits exactly one emulator and no real user.
//
// The `<trust-anchors>` block is deliberate, not decoration: declaring a
// `<base-config>` replaces the platform default wholesale, so leaving it out
// would drop the system CA store and break every `https://` connection the
// app makes. Spelling it out keeps HTTPS working exactly as before; the only
// behaviour this plugin changes is that cleartext stops being refused.
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require('@expo/config-plugins')
const { promises: fs } = require('node:fs')
const path = require('node:path')

const RESOURCE_NAME = 'network_security_config'
const MANIFEST_VALUE = `@xml/${RESOURCE_NAME}`

// Note the comment below carries no double hyphen. XML forbids `--` inside a
// comment, and `aapt2` enforces it: an earlier draft wrote "expo prebuild
// --clean" there and the resource failed to compile with
// `The string "--" is not permitted within comments`, 17 minutes into a
// release build. Generation is not compilation — this file is only proven by
// a build that gets as far as `:app:mergeReleaseResources`.
const NETWORK_SECURITY_CONFIG = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withCleartextTraffic.js — edit that, not this file.
     This whole folder is CNG output and every clean prebuild rewrites it. -->
<network-security-config>
    <base-config cleartextTrafficPermitted="true">
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
`

function withCleartextTrafficResource(config) {
  return withDangerousMod(config, [
    'android',
    async config => {
      const xmlDir = path.join(config.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'xml')

      await fs.mkdir(xmlDir, { recursive: true })
      await fs.writeFile(path.join(xmlDir, `${RESOURCE_NAME}.xml`), NETWORK_SECURITY_CONFIG, 'utf8')

      return config
    }
  ])
}

function withCleartextTrafficManifest(config) {
  return withAndroidManifest(config, config => {
    const application = AndroidConfig.Manifest.getMainApplicationOrThrow(config.modResults)

    application.$['android:networkSecurityConfig'] = MANIFEST_VALUE

    return config
  })
}

function withCleartextTraffic(config) {
  return withCleartextTrafficManifest(withCleartextTrafficResource(config))
}

module.exports = withCleartextTraffic
