#!/usr/bin/env node
/**
 * Generates src/lib/icons.ts from the desktop's apps/desktop/src/lib/icons.ts
 * — the same Tabler alias names (`IconSend as Send`, ...), so the two icon
 * sets can never diverge, plus a hand-written numeric size scale (the
 * desktop's own `iconSize` is Tailwind `size-*` class names, which don't
 * exist in React Native — @tabler/icons-react-native's `<Icon size={N} />`
 * prop needs numbers instead, so that part is NOT generated).
 *
 * Unlike scripts/sync-upstream.mjs, this writes to src/lib/ (this app's own
 * code, not src/upstream/) and is not part of the idempotent vendor sync —
 * it's a one-off/occasional generator, re-run by hand whenever the desktop's
 * icon list changes. Reads the SAME upstream commit recorded in
 * src/upstream/UPSTREAM.json, for one consistent upstream snapshot across
 * everything this repo borrows from hermes-agent.
 *
 * Usage: node scripts/generate-icons.mjs
 * Env:   HERMES_AGENT_ROOT (default ../hermes-agent, relative to repo root)
 */

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, '..')
const UPSTREAM_ROOT = path.resolve(REPO_ROOT, process.env.HERMES_AGENT_ROOT || '../hermes-agent')
const SRC = 'apps/desktop/src/lib/icons.ts'
const DEST = path.join(REPO_ROOT, 'src', 'lib', 'icons.ts')

function fail(message) {
  console.error(`generate-icons: ${message}`)
  process.exit(1)
}

const { commit } = JSON.parse(readFileSync(path.join(REPO_ROOT, 'src', 'upstream', 'UPSTREAM.json'), 'utf8'))

let content
try {
  content = execFileSync('git', ['-C', UPSTREAM_ROOT, 'show', `${commit}:${SRC}`], { encoding: 'utf8' })
} catch {
  fail(`missing upstream file at ${commit}:${SRC}`)
}

// Everything up to and including the IconComponent type re-export is the
// alias table this file ports; iconSize/IconSize (Tailwind classes) below it
// is desktop-only and is replaced with a hand-written numeric scale instead.
const END_MARKER = "export type { Icon as IconComponent } from '@tabler/icons-react'"
const endIndex = content.indexOf(END_MARKER)

if (endIndex === -1) {
  fail(`expected marker not found in ${SRC} — the desktop file's shape changed, update this script: "${END_MARKER}"`)
}

const aliasTable = content.slice(0, endIndex + END_MARKER.length)

const FROM_WEB = /from '@tabler\/icons-react'/g
const importCount = (aliasTable.match(FROM_WEB) ?? []).length

if (importCount !== 2) {
  fail(
    `expected exactly 2 "from '@tabler/icons-react'" occurrences (the import + the IconComponent re-export), found ${importCount}`
  )
}

const rewritten = aliasTable.replace(FROM_WEB, "from '@tabler/icons-react-native'")

const HEADER = `// GENERATED by scripts/generate-icons.mjs from ${SRC} at hermes-agent commit
// ${commit} — do not hand-edit; re-run the script instead. Same alias names
// as the desktop's own icon module (apps/desktop/src/lib/icons.ts), so the
// two icon sets can never diverge.

`

const SIZE_SCALE = `

/**
 * Numeric icon-size scale — the mobile counterpart to the desktop's
 * Tailwind-class \`iconSize\` (React Native's <Icon size={N} /> prop takes a
 * number, not a class name, so this isn't generated from the desktop file;
 * it's picked to land on the same visual sizes as the desktop's size-3
 * through size-6, which are 12/14/16/20/24px).
 */
export const iconSize = {
  xs: 12,
  sm: 14,
  md: 16,
  lg: 20,
  xl: 24
} as const

export type IconSize = keyof typeof iconSize
`

writeFileSync(DEST, HEADER + rewritten + SIZE_SCALE)

const eslintBin = path.join(REPO_ROOT, 'node_modules', 'eslint', 'bin', 'eslint.js')
const prettierBin = path.join(REPO_ROOT, 'node_modules', 'prettier', 'bin', 'prettier.cjs')

execFileSync(process.execPath, [eslintBin, '--fix', DEST], { cwd: REPO_ROOT, stdio: 'inherit' })
execFileSync(process.execPath, [prettierBin, '--write', DEST], { cwd: REPO_ROOT, stdio: 'inherit' })

console.log(`generate-icons: wrote ${path.relative(REPO_ROOT, DEST)}`)
